#WAP TAKE INPUT STRINGS OF EQUAL LENGTH AND THE LENGTH OF STINGS SHOULD BE GREATER
#THAN 5 AND DISPLAY OUTPUT BY COMBINING LAST THREE CHARACTERS FROM THE 1ST STRING
#WITH FIRST THREE CHARACTERS FROM THE SECOND STRING.

str1="PYTHON"
str2="PROGRAMMING"
str3=str1[3:6]+str2[0:3]
print(str3)
